// Property schema, drives the progressive-disclosure inspector.
import { UNITS } from './composer-css';

export const SCHEMA = {
  typography: [
    { k: 'fontFamily',      label: 'Font Family',     type: 'select-custom', options: [
      'Inter','Roboto','Open Sans','Lato','Montserrat','Poppins','Nunito','Nunito Sans','Source Sans Pro','Source Sans 3','Raleway','Oswald','Mulish','Work Sans','Karla','PT Sans','Noto Sans','DM Sans','Manrope','Plus Jakarta Sans','Rubik','IBM Plex Sans','Helvetica','Helvetica Neue','Arial','Verdana','Tahoma','Trebuchet MS','SF Pro','SF Pro Display','SF Pro Text',
      'Playfair Display','Merriweather','Lora','PT Serif','Source Serif Pro','Source Serif 4','Crimson Text','Cormorant Garamond','Libre Baskerville','EB Garamond','Bitter','Georgia','Times New Roman','Garamond',
      'JetBrains Mono','Fira Code','Source Code Pro','IBM Plex Mono','Roboto Mono','Inconsolata','Courier New','Menlo','Consolas','monospace',
      'system-ui','ui-sans-serif','ui-serif','ui-monospace','sans-serif','serif','cursive','fantasy',
    ], w: '1/1', common: true },
    { k: 'fontSize',        label: 'Font Size',       type: 'length', units: 'fontSize', common: true, w: '1/3' },
    { k: 'fontWeight',      label: 'Font Weight',     type: 'select', optionsKey: 'fontWeight', common: true, w: '1/3' },
    { k: 'lineHeight',      label: 'Line Height',     type: 'length', units: 'lineHeight', common: true, w: '1/3' },
    { k: 'letterSpacing',   label: 'Letter Spacing',  type: 'length', units: 'spacing', w: '1/2' },
    { k: 'wordSpacing',     label: 'Word Spacing',    type: 'length', units: 'spacing', w: '1/2' },
    { k: 'textAlign',       label: 'Text Align',      type: 'seg-align', w: '1/1', common: true },
    { k: 'textColor',       label: 'Color',           type: 'color', w: '1/1', global: 'color', common: true },
    { k: 'fontStyle',       label: 'Font Style',      type: 'select', optionsKey: 'fontStyle', w: '1/2' },
    { k: 'textTransform',   label: 'Text Transform',  type: 'select', optionsKey: 'textTransform', w: '1/2' },
    { k: 'textDecoration',  label: 'Text Decoration', type: 'select', optionsKey: 'textDecoration', w: '1/2' },
    { k: 'textDecorationStyle', label: 'Decoration Style', type: 'select', optionsKey: 'textDecorationStyle', w: '1/2' },
    { k: 'whiteSpace',      label: 'White Space',     type: 'select', optionsKey: 'whiteSpace', w: '1/2' },
    { k: 'wordBreak',       label: 'Word Break',      type: 'select', optionsKey: 'wordBreak', w: '1/2' },
    { k: 'overflowWrap',    label: 'Overflow Wrap',   type: 'select', optionsKey: 'overflowWrap', w: '1/2' },
    { k: 'fontVariant',     label: 'Font Variant',    type: 'select', optionsKey: 'fontVariant', w: '1/2' },
    { k: 'fontStretch',     label: 'Font Stretch',    type: 'select', optionsKey: 'fontStretch', w: '1/2' },
    { k: 'direction',       label: 'Direction',       type: 'select', optionsKey: 'direction', w: '1/2' },
    { k: 'writingMode',     label: 'Writing Mode',    type: 'select', optionsKey: 'writingMode', w: '1/2' },
    { k: 'textOrientation', label: 'Text Orientation',type: 'select', optionsKey: 'textOrientation', w: '1/2' },
    { k: 'textShadow',      label: 'Text Shadow',     type: 'text-shadow', w: '1/1', global: 'color' },
  ],

  layout: [
    { k: 'display',     label: 'Display',     type: 'select', optionsKey: 'display', common: true, w: '1/3' },
    { k: 'position',    label: 'Position',    type: 'select', optionsKey: 'position', common: true, w: '1/3' },
    { k: 'boxSizing',   label: 'Box Sizing',  type: 'select', optionsKey: 'boxSizing', w: '1/3' },
    { k: 'visibility',  label: 'Visibility',  type: 'select', optionsKey: 'visibility', w: '1/3' },
    { k: 'width',       label: 'Width',       type: 'length', units: 'size', w: '1/2', common: true },
    { k: 'height',      label: 'Height',      type: 'length', units: 'size', w: '1/2', common: true },
    { k: 'minWidth',    label: 'Min W',       type: 'length', units: 'size', w: '1/4' },
    { k: 'maxWidth',    label: 'Max W',       type: 'length', units: 'size', w: '1/4' },
    { k: 'minHeight',   label: 'Min H',       type: 'length', units: 'size', w: '1/4' },
    { k: 'maxHeight',   label: 'Max H',       type: 'length', units: 'size', w: '1/4' },
    // Visual inset editor, one composite control (a box with each side's
    // offset on its edge + a centre input for the selected side). It reads/
    // writes the same top/right/bottom/left keys, which are kept in the schema
    // below (showWhen:false) so the CSS parser/cascade still resolve them.
    { k: 'inset',       label: 'Inset',       type: 'inset', showWhen: (p) => p.position && p.position !== 'static', autoShowWhen: () => true, w: '1/1' },
    { k: 'top',         label: 'Top',         type: 'length', units: 'length', showWhen: () => false, w: '1/4' },
    { k: 'right',       label: 'Right',       type: 'length', units: 'length', showWhen: () => false, w: '1/4' },
    { k: 'bottom',      label: 'Bottom',      type: 'length', units: 'length', showWhen: () => false, w: '1/4' },
    { k: 'left',        label: 'Left',        type: 'length', units: 'length', showWhen: () => false, w: '1/4' },
    { k: 'zIndex',      label: 'Z-Index',     type: 'number', placeholder: 'auto', w: '1/2' },
    { k: 'overflow',    label: 'Overflow',    type: 'select', optionsKey: 'overflow', w: '1/2' },
    { k: 'overflowX',   label: 'Overflow X',  type: 'select', optionsKey: 'overflow', w: '1/2' },
    { k: 'overflowY',   label: 'Overflow Y',  type: 'select', optionsKey: 'overflow', w: '1/2' },
    { k: 'float',       label: 'Float',       type: 'select', optionsKey: 'float', w: '1/2' },
    { k: 'clear',       label: 'Clear',       type: 'select', optionsKey: 'clear', w: '1/2' },
    { k: 'cursor',      label: 'Cursor',      type: 'select', optionsKey: 'cursor', w: '1/2' },
    { k: 'pointerEvents', label: 'Pointer Events', type: 'select', optionsKey: 'pointerEvents', w: '1/2' },
    { k: 'userSelect',  label: 'User Select', type: 'select', optionsKey: 'userSelect', w: '1/2' },
    { k: 'resize',      label: 'Resize',      type: 'select', optionsKey: 'resize', w: '1/2' },
    { k: 'objectFit',   label: 'Object Fit',  type: 'select', optionsKey: 'objectFit', w: '1/2' },
    { k: 'objectPosition', label: 'Object Position', type: 'select', optionsKey: 'objectPosition', w: '1/2' },
    { k: 'flexDirection',  label: 'Flex Direction',  type: 'select', optionsKey: 'flexDirection', group: 'Flex Container', autoShowWhen: (p) => p.display === 'flex', w: '1/2' },
    { k: 'flexWrap',       label: 'Flex Wrap',       type: 'select', optionsKey: 'flexWrap', group: 'Flex Container', autoShowWhen: (p) => p.display === 'flex', w: '1/2' },
    { k: 'justifyContent', label: 'Justify Content', type: 'select', optionsKey: 'justifyContent', group: 'Flex Container', autoShowWhen: (p) => p.display === 'flex', w: '1/2' },
    { k: 'alignItems',     label: 'Align Items',     type: 'select', optionsKey: 'alignItems', group: 'Flex Container', autoShowWhen: (p) => p.display === 'flex', w: '1/2' },
    { k: 'alignContent',   label: 'Align Content',   type: 'select', optionsKey: 'alignContent', group: 'Flex Container', autoShowWhen: (p) => p.display === 'flex', w: '1/2' },
    { k: 'rowGap',         label: 'Row Gap',         type: 'length', units: 'gap', group: 'Gaps',   autoShowWhen: (p) => p.display === 'flex' || p.display === 'grid', w: '1/2' },
    { k: 'columnGap',      label: 'Column Gap',      type: 'length', units: 'gap', group: 'Gaps', autoShowWhen: (p) => p.display === 'flex' || p.display === 'grid', w: '1/2' },
    { k: 'alignSelf',      label: 'Align Self',      type: 'select', optionsKey: 'alignSelf', group: 'Flex Item', w: '1/2' },
    { k: 'justifySelf',    label: 'Justify Self',    type: 'select', optionsKey: 'justifySelf', group: 'Flex Item', w: '1/2' },
    { k: 'flexGrow',       label: 'Flex Grow',       type: 'number', placeholder: '0', group: 'Flex Item', w: '1/2' },
    { k: 'flexShrink',     label: 'Flex Shrink',     type: 'number', placeholder: '1', group: 'Flex Item', w: '1/2' },
    { k: 'flexBasis',      label: 'Flex Basis',      type: 'length', units: 'size', group: 'Flex Item', w: '1/2' },
    { k: 'order',          label: 'Order',           type: 'number', placeholder: '0', group: 'Flex Item', w: '1/2' },
    { k: 'gridTemplateColumns', label: 'Grid Template Columns', type: 'text-mono', w: '1/1', placeholder: '1fr 1fr 1fr', group: 'Grid' },
    { k: 'gridTemplateRows',    label: 'Grid Template Rows',    type: 'text-mono', w: '1/1', placeholder: 'auto auto', group: 'Grid' },
    { k: 'gridAutoFlow',        label: 'Grid Auto Flow', type: 'select', optionsKey: 'gridAutoFlow', group: 'Grid', w: '1/2' },
  ],

  background: [
    { k: 'bgColor',       label: 'Color',      type: 'color', w: '1/1', global: 'color', common: true },
    { k: 'bgImage',       label: 'Image',     type: 'media-image', w: '1/1', placeholder: 'url(https://…)', common: true },
    { k: 'bgGradient',    label: 'Gradient',  type: 'gradient',  w: '1/1' },
    { k: 'bgRepeat',      label: 'Repeat',     type: 'select', optionsKey: 'bgRepeat', w: '1/2' },
    { k: 'bgSize',        label: 'Size',       type: 'select', optionsKey: 'bgSize', w: '1/2' },
    { k: 'bgPosition',    label: 'Position',   type: 'select', optionsKey: 'bgPosition', w: '1/2' },
    { k: 'bgAttachment',  label: 'Attachment', type: 'select', optionsKey: 'bgAttachment', w: '1/2' },
    { k: 'bgOrigin',      label: 'Origin',     type: 'select', optionsKey: 'bgOrigin', w: '1/2' },
    { k: 'bgClip',        label: 'Clip',       type: 'select', optionsKey: 'bgClip', w: '1/2' },
    { k: 'bgBlendMode',   label: 'Blend Mode', type: 'select', optionsKey: 'bgBlendMode', w: '1/1' },
  ],

  border: [
    { k: 'width',  label: 'Width',  type: 'length', units: 'px', common: true, w: '1/1' },
    { k: 'style',  label: 'Style',  type: 'select', optionsKey: 'borderStyle', common: true, w: '1/2' },
    { k: 'color',  label: 'Color',  type: 'color', w: '1/1', global: 'color', common: true },
    { k: 'radius', label: 'Radius (all)', type: 'length', units: 'radius', w: '1/1', common: true },
    { k: 'bwTop',    label: 'Top',    type: 'length', units: 'px', group: 'Per-side width', w: '1/4' },
    { k: 'bwRight',  label: 'Right',  type: 'length', units: 'px', group: 'Per-side width', w: '1/4' },
    { k: 'bwBottom', label: 'Bottom', type: 'length', units: 'px', group: 'Per-side width', w: '1/4' },
    { k: 'bwLeft',   label: 'Left',   type: 'length', units: 'px', group: 'Per-side width', w: '1/4' },
    { k: 'rTL', label: 'TL', type: 'length', units: 'radius', group: 'Per-corner radius', w: '1/4' },
    { k: 'rTR', label: 'TR', type: 'length', units: 'radius', group: 'Per-corner radius', w: '1/4' },
    { k: 'rBR', label: 'BR', type: 'length', units: 'radius', group: 'Per-corner radius', w: '1/4' },
    { k: 'rBL', label: 'BL', type: 'length', units: 'radius', group: 'Per-corner radius', w: '1/4' },
  ],

  effects: [
    { k: 'opacity',       label: 'Opacity',      type: 'opacity', placeholder: '1', common: true, w: '1/2' },
    { k: 'shadow',        label: 'Shadow Preset', type: 'select', optionsKey: 'shadowPresets', w: '1/1', common: true },
    { k: 'boxShadow',     label: 'Box Shadow',   type: 'text-mono', w: '1/1', placeholder: '0 4px 12px rgba(0,0,0,.12)' },
    { k: 'mixBlendMode',  label: 'Mix Blend',    type: 'select', optionsKey: 'mixBlendMode', w: '1/2' },
    { k: 'blur',       label: 'Blur',       type: 'length', units: 'px', group: 'Filter', w: '1/2' },
    { k: 'brightness', label: 'Brightness', type: 'length', units: 'pct', group: 'Filter', w: '1/2' },
    { k: 'contrast',   label: 'Contrast',   type: 'length', units: 'pct', group: 'Filter', w: '1/2' },
    { k: 'saturate',   label: 'Saturate',   type: 'length', units: 'pct', group: 'Filter', w: '1/2' },
    { k: 'hueRotate',  label: 'Hue Rotate', type: 'length', units: 'angle', group: 'Filter', w: '1/2' },
    { k: 'grayscale',  label: 'Grayscale',  type: 'length', units: 'pct', group: 'Filter', w: '1/2' },
    { k: 'invert',     label: 'Invert',     type: 'length', units: 'pct', group: 'Filter', w: '1/2' },
    { k: 'sepia',      label: 'Sepia',      type: 'length', units: 'pct', group: 'Filter', w: '1/2' },
    { k: 'translateX', label: 'Translate X', type: 'length', units: 'length', group: 'Transform', w: '1/2' },
    { k: 'translateY', label: 'Translate Y', type: 'length', units: 'length', group: 'Transform', w: '1/2' },
    { k: 'rotate',     label: 'Rotate',      type: 'length', units: 'angle',  group: 'Transform', w: '1/2' },
    { k: 'scale',      label: 'Scale',       type: 'number', placeholder: '1', group: 'Transform', w: '1/2' },
    { k: 'skewX',      label: 'Skew X',      type: 'length', units: 'angle',  group: 'Transform', w: '1/2' },
    { k: 'skewY',      label: 'Skew Y',      type: 'length', units: 'angle',  group: 'Transform', w: '1/2' },
    { k: 'transformOrigin', label: 'Transform Origin', type: 'select', optionsKey: 'objectPosition', group: 'Transform', w: '1/1' },
    { k: 'transitionProperty', label: 'Property', type: 'text-mono', w: '1/1', placeholder: 'all', group: 'Transition' },
    { k: 'transitionDuration', label: 'Duration', type: 'length', units: 'time', group: 'Transition', w: '1/2' },
    { k: 'transitionDelay',    label: 'Delay',    type: 'length', units: 'time', group: 'Transition', w: '1/2' },
    { k: 'transitionTiming',   label: 'Timing',   type: 'select', optionsKey: 'transitionTiming', group: 'Transition', w: '1/1' },
  ],
};

export function resolveUnits(name) {
  if (Array.isArray(name)) return name;
  if (name === 'pct')    return ['%'];
  if (name === 'px')     return ['px','em','rem'];
  return UNITS[name] || ['px','%','em','rem','vw','vh'];
}
