// CSS property dictionary — units, keywords, and field metadata.

export const UNITS = {
  length:     ['px', '%', 'em', 'rem', 'vw', 'vh', 'vmin', 'vmax', 'ch', 'ex', 'pt', 'auto'],
  lengthNeg:  ['px', '%', 'em', 'rem', 'vw', 'vh', 'vmin', 'vmax', 'ch', 'ex', 'pt', 'auto'],
  fontSize:   ['px', 'rem', 'em', '%', 'vw', 'vh', 'pt'],
  spacing:    ['px', 'em', 'rem', '%'],
  lineHeight: ['em', '%', 'px', 'rem', 'unitless'],
  radius:     ['px', '%', 'em', 'rem'],
  px:         ['px', 'em', 'rem'],
  gap:        ['px', '%', 'em', 'rem', 'vw', 'vh'],
  size:       ['px', '%', 'em', 'rem', 'vw', 'vh', 'auto', 'fit-content', 'max-content', 'min-content'],
  time:       ['ms', 's'],
  angle:      ['deg', 'rad', 'grad', 'turn'],
  resolution: ['dppx', 'dpi', 'dpcm'],
};

export const OPTS = {
  display: [
    'block','inline','inline-block','flex','inline-flex','grid','inline-grid',
    'table','table-row','table-cell','list-item','contents','flow-root','none',
  ],
  position: ['static','relative','absolute','fixed','sticky'],
  overflow: ['visible','hidden','scroll','auto','clip'],
  visibility: ['visible','hidden','collapse'],
  boxSizing: ['content-box','border-box'],
  float: ['none','left','right','inline-start','inline-end'],
  clear: ['none','left','right','both','inline-start','inline-end'],
  cursor: [
    'auto','default','pointer','text','wait','help','move','not-allowed',
    'grab','grabbing','crosshair','zoom-in','zoom-out','ew-resize','ns-resize',
    'nesw-resize','nwse-resize','none','progress','cell','copy','alias',
  ],
  pointerEvents: ['auto','none'],
  userSelect: ['auto','none','text','all','contain'],
  fontWeight: [
    ['100','Thin · 100'],['200','Extra Light · 200'],['300','Light · 300'],
    ['400','Regular · 400'],['500','Medium · 500'],['600','Semibold · 600'],
    ['700','Bold · 700'],['800','Extrabold · 800'],['900','Black · 900'],
    ['normal','normal'],['bold','bold'],['lighter','lighter'],['bolder','bolder'],
  ],
  fontStyle: ['normal','italic','oblique'],
  textAlign: ['left','center','right','justify','start','end','match-parent'],
  textTransform: ['none','uppercase','lowercase','capitalize','full-width','full-size-kana'],
  textDecoration: ['none','underline','overline','line-through','blink'],
  textDecorationStyle: ['solid','double','dotted','dashed','wavy'],
  whiteSpace: ['normal','nowrap','pre','pre-line','pre-wrap','break-spaces'],
  wordBreak: ['normal','break-all','keep-all','break-word'],
  overflowWrap: ['normal','break-word','anywhere'],
  fontVariant: ['normal','small-caps','all-small-caps','petite-caps','unicase','titling-caps'],
  fontStretch: [
    'ultra-condensed','extra-condensed','condensed','semi-condensed',
    'normal','semi-expanded','expanded','extra-expanded','ultra-expanded',
  ],
  flexDirection: ['row','row-reverse','column','column-reverse'],
  flexWrap: ['nowrap','wrap','wrap-reverse'],
  justifyContent: [
    'flex-start','flex-end','center','space-between','space-around','space-evenly',
    'start','end','left','right','stretch','normal',
  ],
  alignItems: ['stretch','flex-start','flex-end','center','baseline','start','end','self-start','self-end','normal'],
  alignContent: ['normal','flex-start','flex-end','center','space-between','space-around','space-evenly','stretch','start','end','baseline'],
  alignSelf: ['auto','stretch','flex-start','flex-end','center','baseline','start','end','self-start','self-end','normal'],
  justifySelf: ['auto','stretch','start','end','center','left','right','normal'],
  gridAutoFlow: ['row','column','dense','row dense','column dense'],
  bgRepeat: ['no-repeat','repeat','repeat-x','repeat-y','space','round'],
  bgPosition: ['left top','left center','left bottom','center top','center center','center bottom','right top','right center','right bottom'],
  bgSize: ['auto','cover','contain'],
  bgAttachment: ['scroll','fixed','local'],
  bgOrigin: ['padding-box','border-box','content-box'],
  bgClip: ['border-box','padding-box','content-box','text'],
  bgBlendMode: ['normal','multiply','screen','overlay','darken','lighten','color-dodge','color-burn','hard-light','soft-light','difference','exclusion','hue','saturation','color','luminosity'],
  mixBlendMode: ['normal','multiply','screen','overlay','darken','lighten','color-dodge','color-burn','hard-light','soft-light','difference','exclusion','hue','saturation','color','luminosity','plus-lighter'],
  borderStyle: ['none','hidden','solid','dashed','dotted','double','groove','ridge','inset','outset'],
  objectFit: ['fill','contain','cover','none','scale-down'],
  objectPosition: ['center','top','right','bottom','left','top left','top right','bottom left','bottom right'],
  listStyleType: ['none','disc','circle','square','decimal','decimal-leading-zero','lower-alpha','upper-alpha','lower-roman','upper-roman','lower-greek','armenian','georgian'],
  listStylePosition: ['inside','outside'],
  transitionTiming: ['ease','linear','ease-in','ease-out','ease-in-out','step-start','step-end'],
  animationDirection: ['normal','reverse','alternate','alternate-reverse'],
  animationFillMode: ['none','forwards','backwards','both'],
  animationPlayState: ['running','paused'],
  shadowPresets: [
    'none','sm subtle','md soft','lg elevated','xl floating','2xl dramatic','inset pressed',
  ],
  direction: ['ltr','rtl'],
  writingMode: ['horizontal-tb','vertical-rl','vertical-lr','sideways-rl','sideways-lr'],
  textOrientation: ['mixed','upright','sideways','sideways-right','use-glyph-orientation'],
  resize: ['none','both','horizontal','vertical','block','inline'],
  isolation: ['auto','isolate'],
};
