/**
 * Hatch Smart Block — prompt-based AI section generator.
 *
 * Flow:
 *   1. User types a prompt + picks a vibe preset.
 *   2. Clicks Generate.
 *   3. POST /hatch/v1/ai/generate with the prompt + design tokens.
 *   4. Server-side: read BYOK API key from hatch_ai_api_key option,
 *      call Claude/OpenAI, validate + sanitize HTML, return.
 *   5. Block stores generated HTML in `generated` attribute.
 *   6. Save() outputs the HTML directly — frontend just renders it.
 *
 * Hatch keeps the prompt + vibe so the user can regenerate later.
 *
 * @package HatchBlocks
 */

import { __ } from '@wordpress/i18n';
import { registerBlockType } from '@wordpress/blocks';
import { useBlockProps, InspectorControls } from '@wordpress/block-editor';
import { PanelBody, TextareaControl, SelectControl, Button, Notice, Spinner } from '@wordpress/components';
import { Fragment, useState } from '@wordpress/element';

const VIBES = [
	{ label: 'Minimal',   value: 'minimal' },
	{ label: 'Bold',      value: 'bold' },
	{ label: 'Playful',   value: 'playful' },
	{ label: 'Editorial', value: 'editorial' },
	{ label: 'Corporate', value: 'corporate' },
];

registerBlockType( 'hatch/smart', {
	edit: ( { attributes, setAttributes } ) => {
		const blockProps = useBlockProps( { className: 'hatch-smart' } );
		const [ busy, setBusy ] = useState( false );
		const [ err, setErr ] = useState( '' );

		const generate = async () => {
			if ( ! attributes.prompt.trim() ) {
				setErr( __( 'Add a prompt first.', 'hatch' ) );
				return;
			}
			setBusy( true );
			setErr( '' );
			try {
				const res = await window.wp.apiFetch( {
					path: '/hatch/v1/ai/generate',
					method: 'POST',
					data: { prompt: attributes.prompt, vibe: attributes.vibe },
				} );
				if ( res && res.html ) {
					setAttributes( { generated: res.html, lastModel: res.model || '' } );
				} else if ( res && res.error ) {
					setErr( res.error );
				}
			} catch ( e ) {
				setErr( ( e && e.message ) || __( 'Generation failed.', 'hatch' ) );
			} finally {
				setBusy( false );
			}
		};

		return (
			<Fragment>
				<InspectorControls>
					<PanelBody title={ __( 'Smart Block', 'hatch' ) } initialOpen={ true }>
						<TextareaControl
							label={ __( 'Describe what you want', 'hatch' ) }
							value={ attributes.prompt }
							onChange={ ( v ) => setAttributes( { prompt: v } ) }
							rows={ 5 }
							placeholder={ __( 'Hero section for fintech SaaS — gradient bg, eyebrow, big headline, two CTAs, screenshot mockup right.', 'hatch' ) }
						/>
						<SelectControl
							label={ __( 'Vibe', 'hatch' ) }
							value={ attributes.vibe }
							options={ VIBES }
							onChange={ ( v ) => setAttributes( { vibe: v } ) }
						/>
						<Button variant="primary" onClick={ generate } disabled={ busy } style={ { width: '100%', justifyContent: 'center' } }>
							{ busy ? <Spinner /> : '✨ ' + ( attributes.generated ? __( 'Regenerate', 'hatch' ) : __( 'Generate', 'hatch' ) ) }
						</Button>
						{ err && <Notice status="error" isDismissible={ false }>{ err }</Notice> }
						{ attributes.lastModel && (
							<p style={ { fontSize: '0.8em', color: '#737373', marginTop: 8 } }>
								{ __( 'Generated by', 'hatch' ) }: <code>{ attributes.lastModel }</code>
							</p>
						) }
						<p style={ { fontSize: '0.8em', color: '#737373', marginTop: 8 } }>
							{ __( 'Add your AI API key at Hatch → Blocks tab → Smart Block settings.', 'hatch' ) }
						</p>
					</PanelBody>
				</InspectorControls>
				<div { ...blockProps }>
					{ attributes.generated ? (
						<div className="hatch-smart-rendered" dangerouslySetInnerHTML={ { __html: attributes.generated } } />
					) : (
						<div className="hatch-smart-empty">
							<strong>✨ { __( 'Smart Block', 'hatch' ) }</strong>
							<p>{ __( 'Open the sidebar, describe what you want, click Generate.', 'hatch' ) }</p>
						</div>
					) }
				</div>
			</Fragment>
		);
	},
	save: ( { attributes } ) => {
		const blockProps = useBlockProps.save( {
			className: 'hatch-smart',
			'data-hatch-smart': '',
			'data-vibe': attributes.vibe || '',
		} );
		if ( ! attributes.generated ) return null;
		return <div { ...blockProps } dangerouslySetInnerHTML={ { __html: attributes.generated } } />;
	},
} );
